import Head from 'next/head';
import Featured from '../components/Featured';
import axios from 'axios';
import PizzaList from '../components/PizzaList';
import Add from '../components/Add';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import AddButton from '../components/AddButton';

export default function Home({ pizzaList, admin }) {
  const [close, setClose] = useState(true);
  return (
    <div className={styles.container}>
      <Head>
        <title>Pizza Resoraunt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Featured />
      {admin && <AddButton setClose={setClose} />}
      <PizzaList pizzaList={pizzaList} />
      {!close && <Add setClose={setClose} />}
    </div>
  );
}
export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || '';
  let admin = false;
  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }
  const response = await axios.get(
    'https://pizza-goran-full-stack.herokuapp.com/api/products'
  );
  return {
    props: {
      pizzaList: response.data,
      admin,
    },
  };
};
